spring:
  profiles:
    active: local
  mongodb:
    embedded:
      version: 3.4.5

---
spring:
  config:
    activate:
      on-profile:
        - local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local

---
logging:
  level:
    root: debug